debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.example.board: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  jpa:
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.default_batch_fetch_size: 100
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  datasource:
    url: jdbc:mysql://192.168.0.100:3306/board?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ldy
    password: super1234@
  sql.init.mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
